spring.application.name=RikkeiBank-Project

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/rikkeibank_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=002203Huylam!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT Configuration
# 256-bit hex secret key
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 5 minutes in ms
app.jwt.access-token-expiration=300000
# 1 day in ms
app.jwt.refresh-token-expiration=86400000
